# Generated by Django 3.1.7 on 2021-04-27 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida1',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida1',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
